; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:motor_dmx]
platform = espressif32
board = upesy_wroom
framework = arduino
; Force local esp_dmx fork from this repository.
lib_extra_dirs = lib
build_flags =
	-Ilib/esp_dmx/src
upload_speed = 115200
upload_flags = 
    --before=no_reset
    --after=hard_reset
    --chip=esp32
monitor_dtr = 0
monitor_rts = 0
monitor_port = COM6
upload_port = COM6
lib_deps = 
	gin66/FastAccelStepper@^0.30.0
	fastled/FastLED@^3.8.0
monitor_speed = 115200
build_src_filter = +<motor_dmx/*.cpp>

[env:led_dimmer]
platform = espressif32
board = upesy_wroom
framework = arduino
upload_protocol = esptool
; Force local esp_dmx fork from this repository.
lib_extra_dirs = lib
build_flags =
    -Ilib/esp_dmx/src
lib_deps = 
	fastled/FastLED@^3.8.0
upload_speed = 115200
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
build_src_filter = +<led_dimmer/*.cpp>

[env:strobe_4ch]
platform = espressif32
board = upesy_wroom
framework = arduino
upload_protocol = esptool
; Force local esp_dmx fork from this repository.
lib_extra_dirs = lib
build_flags =
	-Ilib/esp_dmx/src
upload_speed = 115200
monitor_speed = 115200
monitor_port = COM6
upload_port = COM6
build_src_filter = +<strobe_4ch/*.cpp>

[env:rdm_test]
platform = espressif32
board = upesy_wroom
framework = arduino
upload_protocol = esptool
; Force local esp_dmx fork from this repository.
lib_extra_dirs = lib
build_flags =
	-Ilib/esp_dmx/src
upload_speed = 115200
monitor_speed = 115200
monitor_port = COM6
upload_port = COM6
monitor_dtr = 0
monitor_rts = 0
build_src_filter = +<rdm_test/*.cpp>
